
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hksqbbrxvkteufyubipc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrc3FiYnJ4dmt0ZXVmeXViaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTA3MTgsImV4cCI6MjA1NzM2NjcxOH0.i2jZq1ZK251zSsWGlh2OlOLhNDPpD0nKcl_P6-6LpMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
